#!/usr/bin/env python3
##
## EPITECH PROJECT, 2022
## delivery
## File description:
## 208dowels
##

from sys import argv
from math import sqrt, pow
import csv
from unittest import result

def print_help ():
    print("USAGE")
    print("    ./208dowels O0 O1 O2 O3 O4 O5 O6 O7 O8\n")
    print("DESCRIPTION")
    print("    Oi   size of the observed class")

def dowels ():
    print("USAGE")

def check_argv ():
    res = 0
    for i in range(1, len(argv)):
        if int(argv[i]) > 0:
            res += int(argv[i])
        else:
            exit(84)
    if res != 100:
        exit (84)

if __name__ == "__main__":
    try:
        if len(argv) == 2 and argv[1] == "-h":
            print_help()
        elif len(argv) == 10:
            check_argv()
            dowels()
        else:
            raise Exception("Invalid number of argument\n")
    except Exception as excp:
        print("Error:", excp)
        exit(84)